#!/bin/bash

# Shell pipeline to run pyseer using the kinship matrix generated by gemma
# 3 steps
# 1) Generate kinship matrix using gemma
# 2) Run pyseer mutations
# 3) Run pyseer genes
# Run the script in conda R environment
# The script writes output to the current directory

# Functions
usage () {
	echo "USAGE"
	echo " $0 [options] <phenotype.tab>"
	echo "OPTIONS:"
	echo " -g : directory with genotype files"
	echo " -R : path to file with genes in regions format"
	echo " -S : suffix for pyseer output (default: [mutations|genes].<phenotype>.pyseer.tab)"
	echo " -C : continuous phenotype (default: false)"
	echo " -t : number of threads (default: 1)"
	echo "Please run this script in conda R environment"
}

# Print usage and exit if no arguments
if [ $# -eq 0 ]
then
    	usage
	exit 1
fi

# Parse options
THREADS=1
CONT=false

while getopts 'g:R:S:Ct:' option
do
  	case $option in
		g) GENO=$OPTARG ;;
		R) REGIONS=$OPTARG ;;
		S) SUFFIX=$OPTARG ;;
		C) CONT=true ;;
		t) THREADS=$OPTARG ;;
        esac
done

# skip to parse command line arguments
shift $((OPTIND-1))


# Get positional arguments
PHENO=$(readlink -e $1)

# Modify optional arguments
GENO=$(readlink -e $GENO)
REGIONS=$(readlink -e $REGIONS)

if [ -z $SUFFIX ]
then
	SUFFIX=$(basename $PHENO .tab | sed 's/_phenotype//')
fi

# Creating a log file
#LOG='run-pyseer-gemma.log'

# Starting statements
echo "Running $0"
echo "The phenotye file is $PHENO"
echo "The directory with genotype file is $GENO"
echo "The regions file is $REGIONS"
echo "The suffix for pyseer output files is $SUFFIX"

if $CONT
then
	echo "The phenotype $SUFFIX is continuous"
	CONT='-c'
else
	echo "The phenotype $SUFFIX is binary"
	CONT=''
fi

echo "$0 will use $THREADS threads"
echo ""

# Creating file structure
if [ -f phenotype.tab ]
then
	echo "phenotype.tab already present"
else
	cp $PHENO phenotype.tab
	sed '1d' phenotype.tab | cut -f1 > isolates.txt
fi

# Greate kinship matrix using gemma
mkdir gemma
cd gemma
VCF=$GENO/merged.core90.vcf.gz
Rscript ~/R_functions/vcf_to_bimbam.R $VCF
cut -f2 ../phenotype.tab | sed '1d' > pheno.txt
~/perl5/bin/gemma -g geno.txt -p pheno.txt -gk 1 -o gemma -notsnp
mv output/ gemma_gk1
cd ..
HEADER=$(sed -z 's/\n/,/g' isolates.txt | sed 's/,$//')
eval "$(conda shell.bash hook)"
conda activate base
paste isolates.txt gemma/gemma_gk1/gemma.cXX.txt | csvtk add-header -t -n ,$HEADER > geno.kinship.tab

# Run pyseer
echo "" 
eval "$(conda shell.bash hook)"
conda activate pyseer2

# Use run-pyseer-mutations.sh
mkdir mutations
cd mutations
SUFFIX_M=mutations.$SUFFIX
~/perl5/bin/run-pyseer-mutations.sh $CONT -d .. -g $GENO/mutations $SUFFIX_M
cd ..

# Use run-pyseer-genes.sh
mkdir genes
cd genes
SUFFIX_G=genes.$SUFFIX
~/perl5/bin/run-pyseer-genes.sh $CONT -d .. -g $GENO/genes -r $REGIONS $SUFFIX_G
cd ..

